import type { Metadata } from "next";
import { Roboto, Space_Grotesk } from "next/font/google";
import "./globals.css";

const geistRobot = Roboto({
  variable: "--font-Roboto",
  subsets: ["latin"],
});

const geistGrotest = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Doctors Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistGrotest.variable} ${geistRobot.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
